import React, { useState, useEffect, useRef } from 'react';
import api from '../../services/api';
import { 
  GraduationCap, 
  LayoutDashboard, 
  BookOpen, 
  Video, 
  FileText, 
  Award, 
  ClipboardList, 
  MessageSquare, 
  BarChart2, 
  Bell, 
  Settings, 
  LogOut, 
  Check, 
  Menu, 
  X,
  Sparkles
} from 'lucide-react';

// Subcomponents imports
import StudentHome from './StudentHome';
import MyCourses from './MyCourses';
import LectureLibrary from './LectureLibrary';
import AINotes from './AINotes';
import AIQuiz from './AIQuiz';
import Assignments from './Assignments';
import AITutor from './AITutor';
import ProgressAnalytics from './ProgressAnalytics';
import Notifications from './Notifications';
import ProfileSettings from './ProfileSettings';

const StudentLayout = ({ user, onLogout }) => {
  // Navigation & UI Layout State
  const [activeTab, setActiveTab] = useState('dashboard');
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [toast, setToast] = useState(null);

  // Toast helper
  const triggerToast = (message, type = 'success') => {
    setToast({ message, type });
    setTimeout(() => setToast(null), 4000);
  };

  // Profile Info State
  const [profile, setProfile] = useState({
    name: user?.name || '',
    rollNo: '',
    email: '',
    degree: '',
    semester: '',
    avatarColor: 'from-indigo-500 to-blue-600',
    phone: '',
    studyGoal: '',
    studyTime: '',
    emailAlerts: true,
    smsAlerts: false,
    darkMode: false
  });

  // Notifications State
  const [notifications, setNotifications] = useState([]);
  const unreadNotificationsCount = notifications.filter(n => !n.read).length;

  const markAllNotificationsRead = () => {
    setNotifications(notifications.map(n => ({ ...n, read: true })));
    triggerToast("All notifications marked as read!");
  };

  // Lecture Library State
  const [lectures, setLectures] = useState([]);
  const [lectureSearch, setLectureSearch] = useState('');
  const [lectureFilter, setLectureFilter] = useState('All');

  const toggleLectureWatched = (id) => {
    setLectures(prev => prev.map(l => {
      if (l.id === id) {
        const nextState = !l.watched;
        triggerToast(`Marked "${l.topic}" as ${nextState ? 'Watched' : 'Unwatched'}`);
        return { ...l, watched: nextState };
      }
      return l;
    }));
  };

  const watchedLecturesCount = lectures.filter(l => l.watched).length;
  const lectureProgressPercent = lectures.length > 0 ? Math.round((watchedLecturesCount / lectures.length) * 100) : 0;

  // My Courses state & data
  const [courses, setCourses] = useState([]);

  // AI Notes State
  const [notes, setNotes] = useState([]);
  const [expandedNoteId, setExpandedNoteId] = useState(null);

  const handleDownloadNote = (title) => {
    triggerToast(`Initializing AI packaging...`);
    setTimeout(() => {
      const textContent = `# Study Guide: ${title}\n\nGenerated by Vidyastra AI\nDate: ${new Date().toLocaleDateString()}\n\nKey Concepts:\n1. Core Definitions\n2. Implementation Details\n3. Examples & Practice Tasks\n\nStudy hard!`;
      const blob = new Blob([textContent], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${title.toLowerCase().replace(/[^a-z0-9]+/g, '_')}_notes.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      triggerToast(`Successfully downloaded notes!`);
    }, 1200);
  };

  // AI Quiz State
  const [practiceQuizzes, setPracticeQuizzes] = useState([]);

  // Load live database content
  useEffect(() => {
    const loadStudentData = async () => {
      try {
        const profRes = await api.getStudentProfile();
        if (profRes.success && profRes.data && profRes.data.length > 0) {
          const fetchedProfile = profRes.data[0];
          setProfile(prev => ({
            ...prev,
            name: fetchedProfile.name || prev.name,
            email: fetchedProfile.email || prev.email,
            rollNo: fetchedProfile.studentId || prev.rollNo,
            degree: fetchedProfile.department || prev.degree,
            semester: `${fetchedProfile.semester}th Semester` || prev.semester
          }));
        }

        const coursesRes = await api.getStudentCourses();
        if (coursesRes && coursesRes.success && coursesRes.data) {
          const mappedCourses = coursesRes.data.map(c => ({
            code: c.courseCode,
            name: c.courseName,
            progress: c.progress || 0,
            instructor: c.instructor || 'TBA',
            bgGradient: c.bgGradient || 'from-blue-500 to-indigo-600',
            category: c.category || ''
          }));
          setCourses(mappedCourses);
        }

        const lecturesRes = await api.getStudentLectures();
        if (lecturesRes && lecturesRes.success && lecturesRes.data) {
          const mappedLectures = lecturesRes.data.map(l => ({
            id: l._id || l.id,
            topic: l.title,
            subject: l.subject || l.courseCode || '',
            duration: l.duration || 'TBA',
            date: new Date(l.uploadDate).toLocaleDateString(),
            watched: false
          }));
          setLectures(mappedLectures);
        }

        const notesRes = await api.getAINotes();
        if (notesRes && notesRes.success && notesRes.data) {
          const mappedNotes = notesRes.data.map(n => ({
            id: n._id || n.id,
            title: n.title,
            subject: n.subject,
            date: new Date(n.createdAt).toLocaleDateString(),
            tags: n.tags || [],
            summary: n.aiSummary || n.content
          }));
          setNotes(mappedNotes);
        }

        const assignmentsRes = await api.getAIAssignment();
        if (assignmentsRes && assignmentsRes.success && assignmentsRes.data) {
          const mappedAssignments = assignmentsRes.data.map(a => ({
            id: a._id || a.id,
            title: a.title,
            subject: a.course,
            dueDate: new Date(a.dueDate).toLocaleDateString(),
            points: 100,
            status: a.status,
            grade: a.feedback ? `${a.marks} / 100` : ''
          }));
          setAssignments(mappedAssignments);
        }

        const notifRes = await api.getStudentNotifications();
        if (notifRes && notifRes.success && notifRes.data) {
          const mappedNotifs = notifRes.data.map(n => ({
            id: n._id || n.id,
            text: n.message || n.text,
            time: new Date(n.createdAt).toLocaleTimeString(),
            read: n.status === 'Read'
          }));
          setNotifications(mappedNotifs);
        }

        // Fetch AI quizzes history
        const quizzesRes = await api.getAIQuiz();
        if (quizzesRes && quizzesRes.success && quizzesRes.data) {
          const mappedQuizzes = quizzesRes.data.map(q => ({
            id: q._id || q.id,
            title: q.title,
            subject: q.subject,
            questions: q.questions ? q.questions.length : 0,
            difficulty: q.difficulty,
            taken: q.status === 'Completed',
            prevScore: `${q.obtainedMarks} / ${q.totalMarks}`
          }));
          setPracticeQuizzes(mappedQuizzes);
          // Tally total quiz score points from completed quizzes
          const totalPoints = quizzesRes.data
            .filter(q => q.status === 'Completed')
            .reduce((sum, q) => sum + (q.obtainedMarks || 0), 0);
          setQuizScorePoints(totalPoints);
        }
      } catch (err) {
        console.error("Failed to load student data from backend", err);
      }
    };

    loadStudentData();
  }, []);

  const [quizScorePoints, setQuizScorePoints] = useState(0);
  const [aiQuizActive, setAiQuizActive] = useState(false);
  const [quizTopic, setQuizTopic] = useState('DSA');
  const [quizDifficulty, setQuizDifficulty] = useState('Medium');
  const [quizGenerating, setQuizGenerating] = useState(false);

  const [activeQuizQuestions, setActiveQuizQuestions] = useState([]);
  const [selectedAnswers, setSelectedAnswers] = useState({});
  const [quizSubmitted, setQuizSubmitted] = useState(false);
  const [quizScore, setQuizScore] = useState(0);

  const startAiQuizGeneration = async () => {
    setQuizGenerating(true);
    try {
      const res = await api.getAIQuiz();
      if (res && res.success && res.data && res.data.length > 0) {
        const activeQuiz = res.data[0];
        setActiveQuizQuestions(activeQuiz.questions || []);
        setSelectedAnswers({});
        setQuizSubmitted(false);
        setQuizScore(0);
        setAiQuizActive(true);
        triggerToast(`AI generated a customized ${quizDifficulty} quiz on ${quizTopic}! ✦`);
      } else {
        triggerToast("No quizzes available in the database. Please create one on the backend.", "info");
      }
    } catch (err) {
      console.error(err);
      triggerToast("Failed to load AI quiz.", "error");
    } finally {
      setQuizGenerating(false);
    }
  };

  const selectAnswer = (questionIndex, optionIndex) => {
    if (quizSubmitted) return;
    setSelectedAnswers(prev => ({
      ...prev,
      [questionIndex]: optionIndex
    }));
  };

  const handleSubmitQuiz = () => {
    if (Object.keys(selectedAnswers).length < activeQuizQuestions.length) {
      alert("Please answer all questions before submitting!");
      return;
    }
    let correctCount = 0;
    activeQuizQuestions.forEach((q, idx) => {
      if (selectedAnswers[idx] === q.correct) {
        correctCount++;
      }
    });
    const pointsGained = correctCount * 20;
    setQuizScore(correctCount);
    setQuizScorePoints(prev => prev + pointsGained);
    setQuizSubmitted(true);
    triggerToast(`Quiz Submitted! Correct answers: ${correctCount}/${activeQuizQuestions.length}. Gained ${pointsGained} pts! 🎉`);
  };

  // Assignments State
  const [assignments, setAssignments] = useState([]);

  const [activeAssignmentSubmit, setActiveAssignmentSubmit] = useState(null);
  const [submissionText, setSubmissionText] = useState('');

  const submitAssignmentAction = async () => {
    if (!submissionText.trim()) {
      alert("Please write or paste your assignment solution before submitting!");
      return;
    }
    try {
      const res = await api.submitStudentAssignment(activeAssignmentSubmit.id, submissionText);
      setAssignments(prev => prev.map(a => {
        if (a.id === activeAssignmentSubmit.id) {
          return { ...a, status: 'Submitted' };
        }
        return a;
      }));
      triggerToast(`Assignment "${activeAssignmentSubmit.title}" submitted successfully! 🚀`);
    } catch (err) {
      console.error(err);
      triggerToast("Failed to submit assignment solution", "error");
    } finally {
      setActiveAssignmentSubmit(null);
      setSubmissionText('');
    }
  };

  // AI Tutor State & Ref
  const [chatMessages, setChatMessages] = useState([
    { sender: 'ai', text: `Hello ${user?.name || 'Student'}! I am your Vidyastra AI Tutor. ✦\nHow can I help you study today? Ask me any questions about your courses or subjects.`, time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }
  ]);
  const [chatInput, setChatInput] = useState('');
  const [aiTyping, setAiTyping] = useState(false);
  const chatBottomRef = useRef(null);

  const tutorSuggestions = [
    { label: "Why is Binary Search O(log n)?" },
    { label: "Can it work on unsorted arrays?" },
    { label: "What is its space complexity?" },
    { label: "Show JavaScript code for it" }
  ];

  const scrollChatToBottom = () => {
    chatBottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollChatToBottom();
  }, [chatMessages, aiTyping]);

  const handleSendChatMessage = async (textToSend) => {
    if (!textToSend.trim()) return;

    const formattedTime = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    const userMsg = { sender: 'user', text: textToSend, time: formattedTime };
    setChatMessages(prev => [...prev, userMsg]);
    setChatInput('');
    setAiTyping(true);

    try {
      const res = await api.askAI(textToSend);
      const replyText = res.answer || res.content || JSON.stringify(res);
      setChatMessages(prev => [...prev, {
        sender: 'ai',
        text: replyText,
        time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      }]);
    } catch (err) {
      setChatMessages(prev => [...prev, {
        sender: 'ai',
        text: "Sorry, I encountered an issue connecting to the Vidyastra AI backend: " + (err.message || err),
        time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      }]);
    } finally {
      setAiTyping(false);
    }
  };

  const handleSaveSettings = (e) => {
    e.preventDefault();
    triggerToast("Updating profile & settings...");
    setTimeout(() => {
      triggerToast("Settings saved successfully!", 'success');
    }, 1000);
  };

  return (
    <div className="vidyastra-container">
      {/* Global CSS Embedded Styles */}
      <style>{`
        .vidyastra-container {
          display: flex;
          min-height: 100vh;
          font-family: var(--sans-font);
          background-color: var(--bg);
          color: var(--text);
          position: relative;
        }
        .sidebar {
          width: 260px;
          background: #0F172A;
          color: white;
          display: flex;
          flex-direction: column;
          position: fixed;
          top: 0;
          bottom: 0;
          left: 0;
          z-index: 1000;
          transition: transform 0.3s ease;
          border-right: 1px solid rgba(255,255,255,0.08);
          box-shadow: 4px 0 20px rgba(15, 23, 42, 0.15);
        }
        .sidebar-brand {
          padding: 24px 20px;
          display: flex;
          align-items: center;
          gap: 12px;
          border-bottom: 1px solid rgba(255,255,255,0.08);
        }
        .brand-logo-circle {
          width: 40px;
          height: 40px;
          border-radius: 10px;
          background: linear-gradient(135deg, var(--primary) 0%, #6366F1 100%);
          display: flex;
          align-items: center;
          justify-content: center;
          box-shadow: 0 4px 12px rgba(79, 70, 229, 0.3);
        }
        .brand-name {
          font-family: var(--heading-font);
          font-size: 18px;
          font-weight: 700;
          background: linear-gradient(to right, #FFFFFF, #E2E8F0);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          letter-spacing: 0.5px;
        }
        .sidebar-menu {
          flex: 1;
          padding: 24px 12px;
          display: flex;
          flex-direction: column;
          gap: 4px;
          overflow-y: auto;
        }
        .menu-item {
          display: flex;
          align-items: center;
          gap: 12px;
          padding: 11px 16px;
          border-radius: 8px;
          color: #94A3B8;
          font-size: 14px;
          font-weight: 500;
          cursor: pointer;
          transition: all var(--transition-fast);
          border: none;
          background: transparent;
          width: 100%;
          text-align: left;
        }
        .menu-item:hover {
          color: white;
          background-color: rgba(255,255,255,0.04);
        }
        .menu-item.active {
          color: white;
          background: var(--primary);
          box-shadow: 0 4px 12px rgba(79, 70, 229, 0.25);
        }
        .sidebar-footer {
          padding: 20px 12px;
          border-top: 1px solid rgba(255,255,255,0.08);
        }
        .logout-btn {
          display: flex;
          align-items: center;
          gap: 12px;
          padding: 12px 16px;
          border-radius: 8px;
          color: #EF4444;
          font-size: 14px;
          font-weight: 600;
          cursor: pointer;
          transition: all var(--transition-fast);
          width: 100%;
          background: transparent;
          border: none;
        }
        .logout-btn:hover {
          background-color: rgba(239, 68, 68, 0.08);
        }
        .main-workspace {
          flex: 1;
          margin-left: 260px;
          min-height: 100vh;
          display: flex;
          flex-direction: column;
          background-color: var(--bg);
          transition: margin-left 0.3s ease;
        }
        .workspace-header {
          height: 70px;
          background-color: white;
          border-bottom: 1px solid var(--border);
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 0 32px;
          position: sticky;
          top: 0;
          z-index: 900;
        }
        .mobile-menu-toggle {
          display: none;
          background: none;
          border: none;
          color: var(--text);
          cursor: pointer;
          padding: 4px;
        }
        .header-title {
          font-family: var(--heading-font);
          font-size: 20px;
          font-weight: 700;
          color: var(--text);
        }
        .header-actions {
          display: flex;
          align-items: center;
          gap: 20px;
        }
        .bell-trigger {
          position: relative;
          cursor: pointer;
          padding: 8px;
          border-radius: 50%;
          transition: background-color var(--transition-fast);
          border: none;
          background: none;
          color: var(--text-muted);
        }
        .bell-trigger:hover {
          background-color: #F1F5F9;
          color: var(--text);
        }
        .bell-badge {
          position: absolute;
          top: 4px;
          right: 4px;
          background-color: var(--danger);
          color: white;
          font-size: 10px;
          font-weight: bold;
          border-radius: 50%;
          width: 16px;
          height: 16px;
          display: flex;
          align-items: center;
          justify-content: center;
          border: 2px solid white;
        }
        .user-avatar-profile {
          display: flex;
          align-items: center;
          gap: 12px;
          cursor: pointer;
        }
        .avatar-circle-sm {
          width: 36px;
          height: 36px;
          border-radius: 50%;
          background: linear-gradient(135deg, #4F46E5 0%, #818CF8 100%);
          color: white;
          font-weight: 700;
          font-size: 13px;
          display: flex;
          align-items: center;
          justify-content: center;
          box-shadow: 0 2px 8px rgba(79, 70, 229, 0.2);
        }
        .user-meta-header {
          display: flex;
          flex-direction: column;
        }
        .user-name-txt {
          font-size: 14px;
          font-weight: 600;
          color: var(--text);
        }
        .user-role-txt {
          font-size: 11px;
          color: var(--text-muted);
        }
        .workspace-content {
          flex: 1;
          padding: 32px;
          overflow-y: auto;
        }
        @media (max-width: 1024px) {
          .sidebar { transform: translateX(-260px); }
          .sidebar.open { transform: translateX(0); }
          .main-workspace { margin-left: 0; }
          .mobile-menu-toggle { display: block; }
          .workspace-header { padding: 0 16px; }
          .workspace-content { padding: 20px 16px; }
        }
        .gorgeous-card {
          background-color: white;
          border: 1px solid var(--border);
          border-radius: var(--radius-md);
          box-shadow: var(--shadow-sm);
          padding: 24px;
          transition: all var(--transition-normal);
        }
        .gorgeous-card:hover { box-shadow: var(--shadow-md); }
        .gradient-banner {
          background: linear-gradient(135deg, #4F46E5 0%, #312E81 100%);
          border-radius: var(--radius-md);
          padding: 24px 32px;
          color: white;
          margin-bottom: 24px;
          display: flex;
          justify-content: space-between;
          align-items: center;
          position: relative;
          overflow: hidden;
        }
        .gradient-banner-bg-sparks {
          position: absolute;
          right: -10px;
          bottom: -20px;
          opacity: 0.15;
          width: 240px;
          height: auto;
          color: white;
        }
        .metrics-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
          gap: 20px;
          margin-bottom: 24px;
        }
        .metric-card-styled {
          background: white;
          border: 1px solid var(--border);
          border-radius: var(--radius-md);
          padding: 20px;
          display: flex;
          align-items: center;
          gap: 16px;
          box-shadow: var(--shadow-sm);
          transition: transform var(--transition-fast), box-shadow var(--transition-fast);
        }
        .metric-card-styled:hover {
          transform: translateY(-2px);
          box-shadow: var(--shadow-md);
        }
        .metric-icon-box {
          width: 48px;
          height: 48px;
          border-radius: 12px;
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 20px;
        }
        .metric-value {
          font-family: var(--heading-font);
          font-size: 22px;
          font-weight: 700;
          color: var(--text);
        }
        .metric-label {
          font-size: 12px;
          color: var(--text-muted);
          font-weight: 500;
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }
        .dashboard-main-grid {
          display: grid;
          grid-template-columns: 2fr 1.2fr;
          gap: 24px;
        }
        @media (max-width: 1024px) {
          .dashboard-main-grid { grid-template-columns: 1fr; }
        }
        .section-header-title {
          font-family: var(--heading-font);
          font-size: 16px;
          font-weight: 700;
          color: var(--text);
          margin-bottom: 16px;
          display: flex;
          align-items: center;
          gap: 8px;
        }
        .btn-join-class {
          background: linear-gradient(135deg, var(--primary) 0%, #6366F1 100%);
          color: white;
          border: none;
          padding: 6px 14px;
          border-radius: 6px;
          font-weight: 600;
          font-size: 12px;
          cursor: pointer;
          transition: opacity var(--transition-fast);
          display: inline-flex;
          align-items: center;
          gap: 6px;
        }
        .btn-join-class:hover { opacity: 0.9; }
        .btn-upcoming {
          background-color: #F1F5F9;
          color: #64748B;
          border: 1px solid #E2E8F0;
          padding: 6px 14px;
          border-radius: 6px;
          font-weight: 600;
          font-size: 12px;
          cursor: not-allowed;
        }
        .vidyastra-toast {
          position: fixed;
          bottom: 24px;
          right: 24px;
          background-color: #0F172A;
          color: white;
          padding: 12px 24px;
          border-radius: 10px;
          box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.3);
          z-index: 2000;
          display: flex;
          align-items: center;
          gap: 10px;
          font-size: 14px;
          font-weight: 500;
          border-left: 4px solid var(--primary);
          animation: slideUp 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards;
        }
        .courses-grid-cards {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
          gap: 24px;
        }
        .course-fancy-card {
          background: white;
          border: 1px solid var(--border);
          border-radius: var(--radius-md);
          overflow: hidden;
          box-shadow: var(--shadow-sm);
          transition: all var(--transition-normal);
        }
        .course-fancy-card:hover {
          transform: translateY(-4px);
          box-shadow: var(--shadow-lg);
        }
        .course-fancy-header {
          padding: 24px;
          color: white;
          position: relative;
        }
        .course-fancy-body {
          padding: 24px;
          display: flex;
          flex-direction: column;
          gap: 16px;
        }
        .fancy-progress-bar-container {
          background-color: #F1F5F9;
          height: 8px;
          border-radius: 4px;
          overflow: hidden;
          width: 100%;
        }
        .fancy-progress-bar-fill {
          height: 100%;
          border-radius: 4px;
          transition: width 0.8s ease-out;
        }
        .fancy-table-container {
          width: 100%;
          overflow-x: auto;
          border-radius: var(--radius-md);
          border: 1px solid var(--border);
          background-color: white;
        }
        .fancy-table {
          width: 100%;
          border-collapse: collapse;
          text-align: left;
          font-size: 14px;
        }
        .fancy-table th {
          background-color: #F8FAFC;
          padding: 16px;
          font-weight: 600;
          color: var(--text-muted);
          border-bottom: 1px solid var(--border);
          font-size: 12px;
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }
        .fancy-table td {
          padding: 16px;
          border-bottom: 1px solid var(--border);
          vertical-align: middle;
        }
        .fancy-table tr:last-child td { border-bottom: none; }
        .badge-status {
          font-size: 11px;
          font-weight: 700;
          padding: 4px 8px;
          border-radius: 9999px;
          display: inline-flex;
          align-items: center;
          gap: 4px;
        }
        .badge-status.pending { background-color: #FEF3C7; color: #D97706; }
        .badge-status.submitted { background-color: #DBEAFE; color: #2563EB; }
        .badge-status.graded { background-color: #D1FAE5; color: #059669; }
        .chat-container {
          background-color: white;
          border: 1px solid var(--border);
          border-radius: var(--radius-md);
          height: 520px;
          display: flex;
          flex-direction: column;
          overflow: hidden;
        }
        .chat-messages-scroll {
          flex: 1;
          padding: 24px;
          overflow-y: auto;
          display: flex;
          flex-direction: column;
          gap: 16px;
          background-color: #F8FAFC;
        }
        .chat-bubble {
          max-width: 75%;
          padding: 14px 18px;
          border-radius: 14px;
          font-size: 14px;
          line-height: 1.5;
          position: relative;
        }
        .chat-bubble.ai {
          background-color: white;
          color: var(--text);
          border: 1px solid var(--border);
          align-self: flex-start;
          border-top-left-radius: 2px;
          box-shadow: 0 2px 4px rgba(0,0,0,0.02);
        }
        .chat-bubble.user {
          background-color: var(--primary);
          color: white;
          align-self: flex-end;
          border-top-right-radius: 2px;
          box-shadow: 0 4px 12px rgba(79, 70, 229, 0.15);
        }
        .chat-time {
          font-size: 10px;
          color: var(--text-muted);
          margin-top: 4px;
          display: block;
          text-align: right;
        }
        .chat-bubble.user .chat-time { color: rgba(255, 255, 255, 0.7); }
        .chat-chips-container {
          padding: 12px 24px;
          background-color: white;
          border-top: 1px solid var(--border);
          display: flex;
          gap: 8px;
          overflow-x: auto;
          flex-shrink: 0;
        }
        .chat-chip {
          padding: 6px 12px;
          border-radius: 9999px;
          background-color: #EEF2FF;
          color: var(--primary);
          font-size: 12px;
          font-weight: 600;
          cursor: pointer;
          transition: all var(--transition-fast);
          border: 1px solid #E0E7FF;
          white-space: nowrap;
        }
        .chat-chip:hover {
          background-color: var(--primary);
          color: white;
          border-color: var(--primary);
        }
        .chat-input-bar {
          padding: 16px 24px;
          background-color: white;
          border-top: 1px solid var(--border);
          display: flex;
          gap: 12px;
          align-items: center;
        }
        .chat-input-field {
          flex: 1;
          height: 40px;
          border-radius: 8px;
          border: 1px solid var(--border);
          padding: 0 16px;
          font-size: 14px;
          outline: none;
        }
        .chat-input-field:focus {
          border-color: var(--primary);
          box-shadow: 0 0 0 2px rgba(79, 70, 229, 0.1);
        }
        .chat-send-btn {
          height: 40px;
          width: 40px;
          border-radius: 8px;
          background-color: var(--primary);
          color: white;
          display: flex;
          align-items: center;
          justify-content: center;
          cursor: pointer;
          border: none;
          transition: opacity var(--transition-fast);
        }
        .chat-send-btn:hover { opacity: 0.9; }
        .chart-svg-container {
          width: 100%;
          height: 200px;
          background-color: #F8FAFC;
          border-radius: 8px;
          border: 1px solid var(--border);
          position: relative;
          overflow: hidden;
          padding: 16px;
        }
        .settings-grid {
          display: grid;
          grid-template-columns: 1.2fr 2fr;
          gap: 32px;
        }
        @media (max-width: 900px) {
          .settings-grid { grid-template-columns: 1fr; }
        }
        .profile-side-card {
          background: white;
          border: 1px solid var(--border);
          border-radius: var(--radius-md);
          padding: 24px;
          text-align: center;
          box-shadow: var(--shadow-sm);
        }
        .profile-avatar-large {
          width: 80px;
          height: 80px;
          border-radius: 50%;
          background: linear-gradient(135deg, #4F46E5 0%, #818CF8 100%);
          color: white;
          font-size: 32px;
          font-weight: 700;
          display: flex;
          align-items: center;
          justify-content: center;
          margin: 0 auto 16px;
          box-shadow: 0 4px 14px rgba(79, 70, 229, 0.3);
        }
        .settings-form-group { margin-bottom: 16px; }
        .settings-form-label {
          display: block;
          font-size: 13px;
          font-weight: 600;
          color: var(--text);
          margin-bottom: 6px;
        }
        .settings-input-control {
          width: 100%;
          height: 40px;
          border-radius: 8px;
          border: 1px solid var(--border);
          padding: 0 16px;
          font-size: 14px;
          outline: none;
          color: var(--text);
        }
        .settings-input-control:focus {
          border-color: var(--primary);
          box-shadow: 0 0 0 2px rgba(79, 70, 229, 0.1);
        }
        .btn-submit-settings {
          background-color: var(--primary);
          color: white;
          border: none;
          padding: 10px 24px;
          border-radius: 8px;
          font-weight: 600;
          cursor: pointer;
          transition: opacity var(--transition-fast);
        }
        .btn-submit-settings:hover { opacity: 0.9; }
        .form-toggle-row {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 12px 0;
          border-bottom: 1px solid var(--border);
        }
        .toggle-switch-input { cursor: pointer; height: 20px; width: 38px; }
        .btn-ai-spark {
          background: linear-gradient(135deg, #4F46E5 0%, #7C3AED 50%, #C084FC 100%);
          color: white;
          border: none;
          padding: 10px 20px;
          border-radius: 8px;
          font-weight: 700;
          font-size: 14px;
          cursor: pointer;
          display: inline-flex;
          align-items: center;
          gap: 8px;
          box-shadow: 0 4px 14px rgba(124, 58, 237, 0.35);
          transition: all var(--transition-fast);
        }
        .btn-ai-spark:hover {
          transform: translateY(-1px);
          box-shadow: 0 6px 20px rgba(124, 58, 237, 0.5);
        }
        .typing-dots {
          display: inline-flex;
          align-items: center;
          gap: 4px;
          padding: 10px 16px;
          background-color: white;
          border: 1px solid var(--border);
          border-radius: 14px;
          align-self: flex-start;
          border-top-left-radius: 2px;
        }
        .typing-dot {
          width: 6px;
          height: 6px;
          background-color: var(--text-muted);
          border-radius: 50%;
          animation: bounce-dot 1.2s infinite ease-in-out;
        }
        .typing-dot:nth-child(2) { animation-delay: 0.2s; }
        .typing-dot:nth-child(3) { animation-delay: 0.4s; }
        @keyframes bounce-dot {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-4px); }
        }
        .note-summary-expandable {
          background-color: #F8FAFC;
          border-top: 1px solid var(--border);
          padding: 16px;
          font-size: 13px;
          color: var(--text-muted);
          animation: slideDownCustom 0.25s ease-out forwards;
        }
        @keyframes slideDownCustom {
          from { opacity: 0; transform: translateY(-8px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .btn-watch-toggle {
          border: none;
          background: transparent;
          cursor: pointer;
          padding: 6px;
          border-radius: 6px;
          display: inline-flex;
          align-items: center;
          justify-content: center;
        }
        .btn-watch-toggle.watched { color: var(--success); background-color: #ECFDF5; }
        .btn-watch-toggle.unwatched { color: var(--text-muted); background-color: #F1F5F9; }
      `}</style>

      {/* Persistent Left-Aligned Sidebar */}
      <aside className={`sidebar ${sidebarOpen ? 'open' : ''}`}>
        <div className="sidebar-brand">
          <div className="brand-logo-circle">
            <GraduationCap className="text-white h-5 w-5" />
          </div>
          <span className="brand-name">Vidyastra AI</span>
        </div>

        <nav className="sidebar-menu">
          <button className={`menu-item ${activeTab === 'dashboard' ? 'active' : ''}`} onClick={() => { setActiveTab('dashboard'); setSidebarOpen(false); }}>
            <LayoutDashboard className="h-4 w-4" />
            <span>Dashboard</span>
          </button>
          
          <button className={`menu-item ${activeTab === 'courses' ? 'active' : ''}`} onClick={() => { setActiveTab('courses'); setSidebarOpen(false); }}>
            <BookOpen className="h-4 w-4" />
            <span>My Courses</span>
          </button>

          <button className={`menu-item ${activeTab === 'lectures' ? 'active' : ''}`} onClick={() => { setActiveTab('lectures'); setSidebarOpen(false); }}>
            <Video className="h-4 w-4" />
            <span>Lecture Library</span>
          </button>

          <button className={`menu-item ${activeTab === 'notes' ? 'active' : ''}`} onClick={() => { setActiveTab('notes'); setSidebarOpen(false); }}>
            <FileText className="h-4 w-4" />
            <span>AI Notes</span>
          </button>

          <button className={`menu-item ${activeTab === 'quiz' ? 'active' : ''}`} onClick={() => { setActiveTab('quiz'); setSidebarOpen(false); }}>
            <Award className="h-4 w-4" />
            <span>AI Quiz</span>
          </button>

          <button className={`menu-item ${activeTab === 'assignments' ? 'active' : ''}`} onClick={() => { setActiveTab('assignments'); setSidebarOpen(false); }}>
            <ClipboardList className="h-4 w-4" />
            <span>Assignments</span>
          </button>

          <button className={`menu-item ${activeTab === 'tutor' ? 'active' : ''}`} onClick={() => { setActiveTab('tutor'); setSidebarOpen(false); }}>
            <MessageSquare className="h-4 w-4" />
            <span>AI Tutor</span>
          </button>

          <button className={`menu-item ${activeTab === 'progress' ? 'active' : ''}`} onClick={() => { setActiveTab('progress'); setSidebarOpen(false); }}>
            <BarChart2 className="h-4 w-4" />
            <span>Progress & Analytics</span>
          </button>

          <button className={`menu-item ${activeTab === 'notifications' ? 'active' : ''}`} onClick={() => { setActiveTab('notifications'); setSidebarOpen(false); }}>
            <Bell className="h-4 w-4" />
            <span style={{ display: 'flex', justifyContent: 'space-between', width: '100%', alignItems: 'center' }}>
              <span>Notifications</span>
              {unreadNotificationsCount > 0 && (
                <span style={{ backgroundColor: '#EF4444', color: 'white', fontSize: '10px', padding: '1px 6px', borderRadius: '10px', fontWeight: 'bold' }}>
                  {unreadNotificationsCount}
                </span>
              )}
            </span>
          </button>

          <button className={`menu-item ${activeTab === 'settings' ? 'active' : ''}`} onClick={() => { setActiveTab('settings'); setSidebarOpen(false); }}>
            <Settings className="h-4 w-4" />
            <span>Profile & Settings</span>
          </button>
        </nav>

        <div className="sidebar-footer">
          <button className="logout-btn" onClick={onLogout}>
            <LogOut className="h-4 w-4" />
            <span>Sign Out</span>
          </button>
        </div>
      </aside>

      {/* Main Workspace */}
      <main className="main-workspace">
        {/* Top Header Navigation */}
        <header className="workspace-header">
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <button className="mobile-menu-toggle" onClick={() => setSidebarOpen(!sidebarOpen)}>
              {sidebarOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}
            </button>
            <h1 className="header-title">
              {activeTab === 'dashboard' && 'Dashboard Overview'}
              {activeTab === 'courses' && 'My Enrolled Courses'}
              {activeTab === 'lectures' && 'Vidyastra Video Archive'}
              {activeTab === 'notes' && 'AI Classroom Summaries'}
              {activeTab === 'quiz' && 'Interactive Assessment Hub'}
              {activeTab === 'assignments' && 'Curriculum Tasks'}
              {activeTab === 'tutor' && 'Vidyastra AI Smart Tutor'}
              {activeTab === 'progress' && 'Academic Performance Engine'}
              {activeTab === 'notifications' && 'System Notifications'}
              {activeTab === 'settings' && 'User Settings Manager'}
            </h1>
          </div>

          <div className="header-actions">
            {/* Notification Bell Shortcut */}
            <button className="bell-trigger" onClick={() => setActiveTab('notifications')}>
              <Bell className="h-5 w-5" />
              {unreadNotificationsCount > 0 && (
                <span className="bell-badge">{unreadNotificationsCount}</span>
              )}
            </button>

            {/* Profile Summary Card */}
            <div className="user-avatar-profile" onClick={() => setActiveTab('settings')}>
              <div className="avatar-circle-sm">
                {profile.name.split(' ').map(n => n[0]).join('')}
              </div>
              <div className="user-meta-header" style={{ display: 'none', md: 'flex' }}>
                <span className="user-name-txt">{profile.name}</span>
                <span className="user-role-txt">{profile.degree}</span>
              </div>
            </div>
          </div>
        </header>

        {/* Workspace Content Scrollable Area */}
        <div className="workspace-content">
          {activeTab === 'dashboard' && (
            <StudentHome 
              profile={profile}
              watchedLecturesCount={watchedLecturesCount}
              lectures={lectures}
              courses={courses}
              lectureProgressPercent={lectureProgressPercent}
              quizScorePoints={quizScorePoints}
              setActiveTab={setActiveTab}
              setLectureFilter={setLectureFilter}
              setQuizTopic={setQuizTopic}
              triggerToast={triggerToast}
            />
          )}

          {activeTab === 'courses' && (
            <MyCourses 
              courses={courses}
              setLectureFilter={setLectureFilter}
              setActiveTab={setActiveTab}
              setQuizTopic={setQuizTopic}
              triggerToast={triggerToast}
            />
          )}

          {activeTab === 'lectures' && (
            <LectureLibrary 
              lectureFilter={lectureFilter}
              setLectureFilter={setLectureFilter}
              lectureSearch={lectureSearch}
              setLectureSearch={setLectureSearch}
              lectures={lectures}
              toggleLectureWatched={toggleLectureWatched}
            />
          )}

          {activeTab === 'notes' && (
            <AINotes 
              notes={notes}
              expandedNoteId={expandedNoteId}
              setExpandedNoteId={setExpandedNoteId}
              handleDownloadNote={handleDownloadNote}
            />
          )}

          {activeTab === 'quiz' && (
            <AIQuiz 
              quizTopic={quizTopic}
              setQuizTopic={setQuizTopic}
              quizDifficulty={quizDifficulty}
              setQuizDifficulty={setQuizDifficulty}
              quizGenerating={quizGenerating}
              startAiQuizGeneration={startAiQuizGeneration}
              aiQuizActive={aiQuizActive}
              setAiQuizActive={setAiQuizActive}
              activeQuizQuestions={activeQuizQuestions}
              selectedAnswers={selectedAnswers}
              quizSubmitted={quizSubmitted}
              quizScore={quizScore}
              selectAnswer={selectAnswer}
              handleSubmitQuiz={handleSubmitQuiz}
              practiceQuizzes={practiceQuizzes}
            />
          )}

          {activeTab === 'assignments' && (
            <Assignments 
              assignments={assignments}
              activeAssignmentSubmit={activeAssignmentSubmit}
              setActiveAssignmentSubmit={setActiveAssignmentSubmit}
              submissionText={submissionText}
              setSubmissionText={setSubmissionText}
              submitAssignmentAction={submitAssignmentAction}
            />
          )}

          {activeTab === 'tutor' && (
            <AITutor 
              chatMessages={chatMessages}
              aiTyping={aiTyping}
              chatBottomRef={chatBottomRef}
              tutorSuggestions={tutorSuggestions}
              chatInput={chatInput}
              setChatInput={setChatInput}
              handleSendChatMessage={handleSendChatMessage}
            />
          )}

          {activeTab === 'progress' && (
            <ProgressAnalytics 
              setLectureFilter={setLectureFilter}
              setActiveTab={setActiveTab}
              triggerToast={triggerToast}
              setExpandedNoteId={setExpandedNoteId}
            />
          )}

          {activeTab === 'notifications' && (
            <Notifications 
              unreadNotificationsCount={unreadNotificationsCount}
              markAllNotificationsRead={markAllNotificationsRead}
              notifications={notifications}
            />
          )}

          {activeTab === 'settings' && (
            <ProfileSettings 
              profile={profile}
              setProfile={setProfile}
              handleSaveSettings={handleSaveSettings}
            />
          )}
        </div>
      </main>

      {/* Floating Status Toast Alert */}
      {toast && (
        <div className={`vidyastra-toast ${toast.type}`}>
          <Sparkles className="h-4 w-4" />
          <span>{toast.message}</span>
        </div>
      )}
    </div>
  );
};

export default StudentLayout;
